### ISSUE TITLE
Drop items not working at all.

### ISSUE THREAD

**Issue by CaramelloDido** [kookehs/risk-of-raindrops#2]
Installed correctly but it doesent drop items at all (single and multiplayer).
Maybe it is incompatible with Loot4all? https://thunderstore.io/package/Sipondo/Loot4All/

**Comment by kookehs** [comment]
As far as I know it isn't compatible. That mod replaces Assembly-CSharp.dll which is basically the game code. My mod relies on Seiko's Mod Loader which patches the the original Assembly-CSharp.dll, though I'm working on porting it to BepInEx as well. I'm not sure if Seiko's Mod Loader is being maintained any more.

**Comment by kookehs** [comment]
DropItems has been ported to BepInEx.
